-- Drops futhead database
DROP DATABASE FUTHEAD;

-- Creates futhead database
CREATE DATABASE FUTHEAD;

-- Uses futhead database;
USE FUTHEAD;

-- DDL for fifa18 table
CREATE TABLE FIFA10
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA11
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA12
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA13
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA14
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA15
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA16
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA17
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

CREATE TABLE FIFA18
(
  NAME      CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  TIER      VARCHAR(6),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);


-- Truncates fifa18 table
TRUNCATE TABLE FIFA18;

-- Charset config
ALTER TABLE FUTHEAD.FIFA10 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA11 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA12 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA13 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA14 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA15 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA16 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA17 CONVERT TO CHARACTER SET UTF8;
ALTER TABLE FUTHEAD.FIFA18 CONVERT TO CHARACTER SET UTF8;

