-- Drops futhead database
DROP DATABASE FUTHEAD;

-- Creates futhead database
CREATE DATABASE FUTHEAD;

-- Drops fifa18 table
-- DROP TABLE FIFA18;

-- create database futhead;
USE FUTHEAD;

-- DDL for fifa18 table
CREATE TABLE FIFA18
(
  NAME     CHAR(30) CHARACTER SET LATIN1 COLLATE LATIN1_BIN,
  CLUB      VARCHAR(50),
  LEAGUE    VARCHAR(50),
  POSITION  VARCHAR(50),
  RATING    INTEGER(2),
  PACE      INTEGER(2),
  SHOOTING  INTEGER(2),
  PASSING   INTEGER(2),
  DRIBBLING INTEGER(2),
  DEFENDING INTEGER(2),
  PHYSICAL  INTEGER(2),
  LOADDATE  TIMESTAMP
);

-- Truncates fifa18 table
-- TRUNCATE TABLE FIFA18;

-- Charset config
ALTER TABLE FUTHEAD.FIFA18 CONVERT TO CHARACTER SET UTF8;

